# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353c9d81a347e945e5c23a5a958dfe39e233af3e71ab9c81af69bf596cbf689afe0268eae8cd131561df8c6ce183958927e2db556c037465b8085c8ad9f9e182

test:
  secret_key_base: 5de70f619fcc0e8252c217353e88d75cbcb1c0e521000c62f4454843e43d3f0530fba8f13e106282d82590eef4f1f74ad29a5715fc8dfddee8d55a4af8f2a901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
